### PR TITLE
Opendkim genzone subdomainmatch

### PR DESCRIPTION
**Pull request by andreasschulze**
this PR contain modifications I use in production since ~4 years

* the generated DNS records contain explicit h=sha256 as SHA1 is deprecated
* do not place a timestamp in opendkim-genzone output so files created at different times are comparable
* correct a logical error Murray indroduced when he merged the initial version of subdomain matching
  - https://sf.net/p/opendkim/feature-requests/187/
  - http://lists.opendkim.org/archive/opendkim/dev/2015/01/2037.html
* be more verbose on skipped subdomains

### CODE REVIEW

**Comment by glts** [comment]
I think #64 already covers this, at least in part.

**Comment by andreasschulze** [comment]
yes, 
8667cd2  addresses the same issue, as the text also mention

**Comment by martinbogo** [comment]
Please don't batch commits.   One PR per issue please, and one commit set per PR.  

Split this into separate PR's, and please make sure to target the development branch.  @mskucherawy and I are working on and testing a new release.

**Comment by andreasschulze** [comment]
this PR is outdated and should be rejected, I created #77, #79, #80 and #81 ...

**Pull request closed without merging**
