### PR TITLE
Fix unknown operator in configure.ac

### PR DESCRIPTION
**Pull request by lechner**
On Debian, the double equal signs `==` produce an error for an unknown
operator. Replace with single equal sign `=`.

### CODE REVIEW

**Comment by hdatma** [comment]
This is a common problem. Linux uses "=" while BSD uses "==". I say, leave "==" when comparing, use "=" when assigning a value to a variable. Besides, this is a very old syntactic standard. Linux should respect it.

**Comment by orlitzky** [comment]
> This is a common problem. Linux uses "=" while BSD uses "==".

Nonsense, the "test" command has been standard for many years:

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html

I quote,

> 
> s1 =  s2
>     True if the strings s1 and s2 are identical; otherwise, false.

Both Linux and BSD work exactly the same in that regard.

**Comment by glts** [comment]
This still causes an `unexpected operator` error to be printed in the Debian build.

It is simply a trivial typo, would be good to merge this.

**Comment by orlitzky** [comment]
The fix is obviously correct, and would reduce the number of pull requests that you have to look at by one. Sounds like a bargain =)

**Pull request merged**
